version: "3.8"

services:
  backend:
    image: mycloud_backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./frontend:/app/frontend
      - ./uploads:/app/uploads
      - ./jobs:/app/jobs
    ports:
      - "5000:5000"
    depends_on:
      - data_base
      - executor

  data_base:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_cloud_db
    ports:
      - "5432:5432"

  executor:
    image: mycloud_executor
    ports:
      - "8000:8000"
    deploy:
      replicas: 3  # ← Escalabilidade horizontal ativada
      restart_policy:
        condition: on-failure

networks:
  default:
    name: my_cloud_network
