apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend        
  ports:
    - port: 5000        # porta interna que o Flask expõe
      targetPort: 5000
      nodePort: 30001   # porta externa fixa em localhost
