apiVersion: v1
kind: Service
metadata:
  name: executor
spec:
  selector:
    app: executor
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor
spec:
  replicas: 2  # ← Escalabilidade horizontal: 2 réplicas
  selector:
    matchLabels:
      app: executor
  template:
    metadata:
      labels:
        app: executor
    spec:
      containers:
        - name: executor
          image: mycloud_executor:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
